export const USER_INCREASE = 'USER_INCREASE';
export const USER_DECREASE = 'USER_DECREASE';
export const GET_EMPLOYEESS_START = 'GET_EMPLOYEESS_START';
export const GET_EMPLOYEESS_SUCCESS = 'GET_EMPLOYEESS_SUCCESS';
export const GET_EMPLOYEESS_FAILURE = 'GET_EMPLOYEESS_FAILURE';
